"""
WinShield Verifier

- Compares pre-install and post-install scan results to assess patch effectiveness.

Expected files:
  - results/winshield_scan_before_install.json  (created by installer)
  - results/winshield_scan_result.json          (generated by running winshield_scanner.py AFTER installation)

The verifier:
  - Loads both JSON files.
  - Compares the 'missing_kbs' sets.
  - Reports:
      * KBs that were previously missing and are now present (fixed).
      * KBs that are still missing.
      * KBs that appear as missing only after installation (regressions).
  - Writes a JSON summary to results/winshield_verify_result.json.
"""

import json
import os
import sys
from typing import Any, Dict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

RESULTS_DIR = os.path.join(SCRIPT_DIR, "results")
os.makedirs(RESULTS_DIR, exist_ok=True)

SCAN_BEFORE_PATH = os.path.join(RESULTS_DIR, "winshield_scan_before_install.json")
SCAN_AFTER_PATH = os.path.join(RESULTS_DIR, "winshield_scan_result.json")
VERIFY_RESULT_PATH = os.path.join(RESULTS_DIR, "winshield_verify_result.json")


def load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def main() -> None:
    if not os.path.isfile(SCAN_BEFORE_PATH):
        print("[X] winshield_scan_before_install.json not found in results/.")
        print("    This file is created by winshield_installer.py before applying updates.")
        print("    Run the installer first, then run winshield_scanner.py again, and re-run this verifier.")
        sys.exit(1)

    if not os.path.isfile(SCAN_AFTER_PATH):
        print("[X] winshield_scan_result.json not found in results/.")
        print("    Run winshield_scanner.py AFTER installing updates to generate the post-install scan.")
        sys.exit(1)

    print("[*] Loading pre-install scan snapshot...")
    before_scan = load_json(SCAN_BEFORE_PATH)
    print("[*] Loading post-install scan snapshot...")
    after_scan = load_json(SCAN_AFTER_PATH)

    before_missing = set(before_scan.get("missing_kbs") or [])
    after_missing = set(after_scan.get("missing_kbs") or [])

    fixed_kbs = sorted(before_missing - after_missing)
    still_missing_kbs = sorted(before_missing & after_missing)
    new_missing_kbs = sorted(after_missing - before_missing)

    before_baseline = before_scan.get("baseline") or {}
    after_baseline = after_scan.get("baseline") or {}

    print()
    print("=== WinShield Verification Summary ===")
    print(f"Pre-install missing KBs: {len(before_missing)}")
    print(f"Post-install missing KBs: {len(after_missing)}")
    print(f"Fixed KBs (no longer missing): {len(fixed_kbs)}")
    print(f"Still missing KBs: {len(still_missing_kbs)}")
    print(f"Newly missing KBs (regressions): {len(new_missing_kbs)}")
    print()

    if fixed_kbs:
        print("KBs fixed by the update process:")
        for kb in fixed_kbs:
            print(f"  - {kb}")
        print()
    else:
        print("No previously-missing KBs were fixed.")
        print()

    if still_missing_kbs:
        print("KBs that remain missing after installation:")
        for kb in still_missing_kbs:
            print(f"  - {kb}")
        print()
    else:
        print("No KBs remain missing from the original missing set.")
        print()

    if new_missing_kbs:
        print("KBs that appear as missing only after installation (regressions):")
        for kb in new_missing_kbs:
            print(f"  - {kb}")
        print()
    else:
        print("No regressions detected (no new missing KBs introduced).")
        print()

    verify_summary = {
        "before": {
            "baseline": {
                "OSName": before_baseline.get("OSName"),
                "DisplayVersion": before_baseline.get("DisplayVersion"),
                "Build": before_baseline.get("Build"),
                "FullBuild": before_baseline.get("FullBuild"),
            },
            "missing_kbs": sorted(before_missing),
        },
        "after": {
            "baseline": {
                "OSName": after_baseline.get("OSName"),
                "DisplayVersion": after_baseline.get("DisplayVersion"),
                "Build": after_baseline.get("Build"),
                "FullBuild": after_baseline.get("FullBuild"),
            },
            "missing_kbs": sorted(after_missing),
        },
        "diff": {
            "fixed": fixed_kbs,
            "still_missing": still_missing_kbs,
            "new_missing": new_missing_kbs,
        },
    }

    with open(VERIFY_RESULT_PATH, "w", encoding="utf-8") as handle:
        json.dump(verify_summary, handle, indent=2)

    print(f"[+] Verification results saved to {VERIFY_RESULT_PATH}")
    print("[*] Verification stage complete.")


if __name__ == "__main__":
    main()
